### ISSUE TITLE
Logo + Basic mockup

### ISSUE THREAD

**Issue by grapemaster** [grapemaster/unlimitedgrapes.com#1]
pending

**Comment by k-sketos** [comment]
![image](https://user-images.githubusercontent.com/83492120/116775461-68b35700-aa63-11eb-84e5-582cd706718a.png)
![image](https://user-images.githubusercontent.com/83492120/116775478-7832a000-aa63-11eb-8620-1bf26cb86135.png)
![image](https://user-images.githubusercontent.com/83492120/116775488-85e82580-aa63-11eb-91dd-d3317e5c62bb.png)
![image](https://user-images.githubusercontent.com/83492120/116784188-36b9e900-aa93-11eb-8dba-f0015ca1706b.png)
